---
- name: Install the LAMP stack
  hosts: Slave
  become: yes
  tasks:
    - name: Copy lamp.sh bash script to Slave node
      copy:
        src: /home/vagrant/lamp.sh
        dest: /home/vagrant/lamp.sh
        mode: 0755

    - name: Execute the lamp.sh bash script to setup LAMP stack
      command: /home/vagrant/lamp.sh

    - name: Create cron job
      cron:
        name: "uptime check"
        minute: "0"
        hour: "0"
        job: "/usr/bin/uptime >> /home/vagrant/uptime.log"
        state: present
